# splitbill-app/docker-compose.yml
version: '3.8'

services:
  splitbill_golang_app:
    build:
      context: . # Membangun image dari direktori ./app
      dockerfile: Dockerfile.golang # Menggunakan Dockerfile kustom untuk Golang
    restart: always # Selalu restart jika crash
    expose:
      - "3000" # Mengekspos port 3000 di dalam jaringan Docker
    networks:
      - app_network

  splitbill_nginx:
    image: nginx:alpine # Menggunakan image Nginx resmi
    ports:
      - "80:8014" # Memetakan port 8014 dari host ke port 8014 di kontainer Nginx
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro # Memasang konfigurasi Nginx
    depends_on:
      - splitbill_golang_app # Memastikan aplikasi Golang siap sebelum Nginx berjalan
    restart: always
    networks:
      - app_network

networks:
  app_network:
    driver: bridge